cloud-gov/pages-builder

- app.js
- newrelic.js
- package.json
Adds new relic configuration to the federalist-builder application
Refs 18F/federalist#441
> Add new relic to application

- README.md
- manifest.yml
- staging_manifest.yml
ref: https://github.com/18F/federalist/issues/902
Hold on merging until the https://github.com/18F/federalist-docker-build/ repo name is actually changed.
> Change "federalist-docker-build" -> "federalist-garden-build"

- README.md
Ref #33. Setup Gemnasium per instructions at https://before-you-ship.18f.gov/security/static-analysis/#gemnasium: https://gemnasium.com/github.com/18F/federalist-builder/
> Setup Gemnasium

- app.js
> Move BuildScheduler require after newrelic require

- .eslintrc.js
- package.json
- yarn.lock
same method as in https://github.com/18F/federalist/pull/1084
> upgrade scanjs plugin and dynamically add rules

- .circleci/config.yml
- src/server.js
- test/cloud-foundry-auth-client-test.js
- test/nocks/cloud-foundry-oauth-token-nock.js
- test/server-test.js
> Deploy to prod 9/15/17

- README.md
Uses content from federalist-docs that will soon be removed as part of https://github.com/18F/federalist-docs/issues/169
> Add "Running Locally" section to README

- README.md
- package.json
- yarn.lock
Looks like we forgot to open a `staging` -> `master` PR in the sprint cycle where these changes were made. Changes are primarily just dependency updates.
> Deploy to production 12/11/17

- yarn.lock
ref https://github.com/18F/federalist/issues/1632
Done via running `yarn upgrade hapi`
> Upgrade hoek version

- package.json
- src/server/healthcheck.js
- src/server/index.js
- test/server-test.js
- yarn.lock
[federalist-builder-snyk-180104.pdf](https://github.com/18F/federalist-builder/files/2729062/federalist-builder-snyk-180104.pdf)
cc @eddietejeda
> upgrade hapi, jsonwebtoken and newrelic

- README.md
Gemnasium is no longer supported. We now use Snyk
> Use snyk for security

- package.json
- yarn.lock
> Release 20200527

- package.json
- yarn.lock
> Release 20200605

- app.js
Missed adding the bull queue to the queue client so the app actually has a bull queue to query.
> Actually add the bull queue to the queue client

- app.js
- src/server/healthcheck.js
- src/server/index.js
- test/server-test.js
Switch to seeing the bull queue stats in the healthcheck
> Switch from SQS to bull queue stats

- ci/pipeline.yml
- ci/vars/example.yml
Fixes issue(s) 18F/federalist#3454.
Proposed changes in this pull request:
- leverage Credhub for concourse variables
> Migrate variables to credhub, remove commented out config

- .cloudgov/manifest.yml
- .env-sample
- app.js
- src/build-scheduler.js
- src/build.js
- src/queue-client.js
- src/server/healthcheck.js
- src/server/index.js
- src/sqs-client.js
- test/build-scheduler-test.js
- test/build-test.js
- test/queue-client-test.js
- test/server-test.js
- test/sqs-client-test.js
Resolves #395 
Not everything is implemented in the most robust way, but as this app has a finite lifetime didn't think it was worth improving.
Not seeing any issues in staging
> 395 queue feature flags

- .circleci/config.yml
- .cloudgov/manifest.yml
- .cloudgov/vars/pages-staging.yml
- .cloudgov/vars/production.yml
- .cloudgov/vars/staging.yml
- ci/pipeline.yml
- Restore Federalist staging to Circle
- migrate Pages staging in Concourse
- add pages-staging space
>  Support pages-staging space and restore Federalist staging to Circle

- ci/pipeline.yml
- Update staging CF creds to use correct deployer in correct `staging` space
None
> Update staging credentials for CI

- .github/workflows/codeql-analysis.yml
> Add codeQL GH Action

- .cloudgov/manifest.yml
- README.md
- env.js
- src/cf-task-pool.js
- test/cf-task-pool-test.js
- Addresses #522 
- Removes legacy code/config
None
> Remove legacy large container config

- package.json
- yarn.lock
- addresses dependabot security advisory
- updates moment.js
- updates other deps
Addresses vuln.
> Update moment and other deps

- .cloudgov/vars/pages-production.yml
- ci/pipeline.yml
- env.js
- Make config more generic to support using lookups rules via CredHub
None
> Update Concourse config to support prod env

- ci/pipeline.yml
- Support multiple envs within the single pipeline config file
None
> Use instance vars in pipeline.yml

- package.json
- yarn.lock
- Update Node JS dependencies
Update runtime dependencies for Node JS using `yarn audit` to identify the packages and applicable updated versions.
> Chore update dependencies 022823
