- .travis.yml
- app.js
- package.json
- src/aws.js
- src/build-scheduler.js
- src/cluster.js
- src/sqs-client.js
- test/build-scheduler.js
- test/cluster-test.js
- test/sqs-client-test.js
This PR represent a major refactor to introduce some modularization that makes it a bit simpler to use and reason about the app.
The motivation for this is moving site builds out of ECS and onto Diego (ref: 18F/federalist#542). It was tough to reason about exactly what needed to be changed and where. Additionally, there was limited confidence that bugs where not being introduced because there were no tests and adding tests to the previous implementation was difficult.
This commit breaks the app into some simple modules to separate the concerns and add the ability to write unit tests.
The new parts are:
- Cluster: Communicates between the app and the ECS cluster. In the future, this will communicate with the cluster in cloud.gov
- SQSClient: Communicates between the app and SQS
- …
> Refactor to provide some modularization

- .travis.yml
- manifest.yml
- staging_manifest.yml
This commit updates travis config and cloud-foundry manifest so that CI will deploy to the AWS GovCloud region instead of to E/W.
> Update config to deploy to GovCloud

- .npmrc
Hapi was installing a version of moment which has a ReDOS vulnerability. The path to that dependency looks like this:
```
hapi@15.2.0 > joi@9.0.4 > moment@2.14.1
```
The `package.json` for `joi@9.0.4` allows joi to install any version of moment that matches `2.x.x`. Unfortunatly this was not happening because Hapi's dependencies are shrinkwrapped.
ref: https://github.com/hapijs/joi/blob/v9.0.4/package.json#L20
ref: https://github.com/hapijs/hapi/blob/v15.0.2/npm-shrinkwrap.json#L45
This commit disables shrinkwrapping when running npm install so that we can get the updated version of moment, and in the future get more recent versions of other packages.
> Disable shrinkwrap when installing npm modules

- src/cluster.js
This commit adjusts the timeout that determines how long builds have to run before they're considered dead to 21 minutes. This is done because some bigger sites (like 18f.gsa.gov) can take 15 - 20 minutes to build.
Ref 18F/federalist#693
> Adjust build timeout to 21 minutes

- .travis.yml
This commit bump the node version we use on Travis to 6.9 which is the LTS and the version we use on cloud.gov.
> Bump Travis's node version to v6.9

- manifest.yml
- staging_manifest.yml
The Federalist web application uses about 60MB-70MB of RAM. With this in mind, this commit scales the memory the app is allocated in cloud.gov from 512MB to 128MB, which should free up some memory in our org, while leaving overhead for memory spikes.
> Reduce instance memory from 512MB to 128MB

- src/build-timeout-reporter.js
- src/cluster.js
- test/build-timeout-reporter.test.js
- test/cluster-test.js
- test/nocks/build-log-callback-nock.js
- test/nocks/build-status-callback-nock.js
This commit adds a new class named `BuildTimeoutReporter`. When a build times out, the class is invoked to send a request to the build's `LOG_CALLBACK` and `STATUS_CALLBACK` URL, alerting the Federalist web application that the build has timed out.
Prior to this commit, no such alert existed, so builds that timed out in this manner appeared to run forever.
Ref #15
Ref 18f/federalist#737
> Report build timeouts back to main Federalist web application

- src/build-timeout-reporter.js
- test/nocks/build-log-callback-nock.js
The BuildTimeoutReporter was using the incorrect params to send a request to create a build log, resulting in build logs not being created when builds timed out. This commit changes the reporter to use the correct params.
> Use correct params for build log request

- manifest.yml
- src/cluster.js
- staging_manifest.yml
- test/cluster-test.js
Prior to this commit, the `BuildTimeoutReporter` was invoked in `Cluster.stopBuild`. This mean a timeout was reported any time a build was stopped, regardless of whether or not the build was stopped because it timed out or because it completed successfully.
This commit adds a new function for stopping builds that timeout and reporting a timeout. It also adds better test coverage for timeout behavior to prevent this error from appearing in the future.
> Only send build timeout message when builds timeout

- src/build-timeout-reporter.js
- test/nocks/build-log-callback-nock.js
The build container now sends build logs to the federalist application
as a base64 enconded string. This commit matches that behavior in the
BuildTimeoutReporter when it reports a build timeout to the build log
API.
> Encode timeout messages as a base64 string

- .travis.yml
- scripts/deploy-travis.sh
This commit changes the way credentials are set during CI deploys so that different environments have different credentials. It also removes the credentials from the Travis config, setting them in Travis env vars instead so they can be rotated without changing the code.
> Select cf creds based on environment

- README.md
- package.json
- yarn.lock
This fixes a potential minor vulnerability in the previously selected version of `hapi`: https://gemnasium.com/github.com/18F/federalist-builder/alerts#alert-5668662
Also fixes some formatting and typos in README.
> Upgrade hapi to latest version

- README.md
- app.js
- manifest.yml
- newrelic.js
- package.json
- staging_manifest.yml
- yarn.lock
This PR fixes how we load New Relic so that it actually works (ref #28). It is implemented similarly to how we did it in https://github.com/18F/federalist/pull/1021.
- Load `NEW_RELIC_LICENSE_KEY` from cloud.gov user-provided service
- Update README.md with new info
- Upgrade newrelic npm depedency
To Do:
> Fix New Relic APM monitoring

- .circleci/config.yml
- scripts/deploy-circle.sh
Fixes broken deployment step from PR #46.
Also remove the custom `yarn` installation because it wasn't actually working and the `node` container from Circle has an up-to-date `yarn` install already.
> Fix deployment from Circle

- .circleci/config.yml
Adds `|| true` to the codeclimate after-build submission. 
That command will fail if a report already exists for a given commit (which is kinda silly, IMO), which means builds cannot be successfully re-run (like if we wanted to rebuild to trigger a re-deployment of a known working version). Using `|| true` will make that command always succeed. We have it setup that way in `federalist` already.
> Don't fail on cc-test-reporter after-build failure

- src/server.js
- test/cloud-foundry-auth-client-test.js
- test/nocks/cloud-foundry-oauth-token-nock.js
- test/server-test.js
Right now, it only checks to make sure that the builder is able
to authenticate with cloud.gov. Other checks can be added in the
future.
Post-merge:
> add healthcheck endpoint for monitoring builder health

- package.json
- yarn.lock
and all its submodules, including `content`, to fix a regex dos issue (ref #53)
> Upgrade hapi to 16.6.0

- package.json
- yarn.lock
ref Gemnasium alert
Had to upgrade `hapi` and `jsonwebtoken` in order to get latest version of moment into `yarn.lock`
> Upgrade to latest version of moment

- package.json
- src/server.js
- src/sqs-client.js
- test/aws-mock.js
- test/server-test.js
- test/sqs-client-test.js
- yarn.lock
I think there are a couple of opportunities for refactoring in the future (or now?):
* Break out the reply logic into a separate response class
* Break out the health check so we can inject it's dependencies — this will let us mock them more easily; obviating the need, for example, the `aws-mocks` library
> Fetch attributes from SQS queue in healthcheck

- .codeclimate.yml
- src/server.js
- src/sqs-client.js
- test/server-test.js
- test/sqs-client-test.js
Actually, remove destructuring completely and instead explicitly use an array of attribute names. 
Also:
- Rename variables and add supporting comments.
- Add an additional test to make sure params are set correctly.
- Nest the queueAttributes in a sub-object, and also add the `ApproximateNumberOfMessagesDelayed` attribute. See screenshot.
- Disable CodeClimate's duplication engine on the `test/` directory.
Even after getting the permissions on the SQS queues properly set, we had a bug that the requested SQS `attributes` parameter was getting destructured too much, so we were asking for an array of attributes that looked like `['A','p','p','r','o','x','i','m','a','t','e' ... ]`
> Make some updates to queueAttributes and fix overly-destructured param.

- manifest.yml
Note that this PR is against `master` and will cause a production redeploy once merged.
I decided to do this directly against `master` (and close #67) since `staging` has some other features from this sprint that we'll want to put through sprint review.
> Update prod sqs queue url

- .circleci/config.yml
- .cloudgov/manifest.yml
- .env-sample.json
- Dockerfile
- README.md
- app.js
- docker-compose.yml
- env.js
- package.json
- src/build-scheduler.js
- src/build.js
- src/bull-queue.js
- src/queue-client.js
- test/build-scheduler-test.js
- test/build-test.js
- test/env.json
- test/helpers.js
- test/queue-client-test.js
- yarn.lock
To move toward an internal queue system, adding bull queue and client to manage queue messages in support of transition from SQS to bull.
To Do:
> Add queue client for bull

- src/bull-queue.js
- src/queue-client.js
- test/queue-client-test.js
Switch to using the `moveToCompleted` job method within the `deleteMessage` method. This way we will be able to view completed job stats, delete older completed jobs based on the number we want to keep or a time delimited task to remove old completed jobs.
> Change from job remove to moveToCompleted on deleteMessage

- .env-sample.json
- README.md
- ci/pipeline.yml
- package.json
- src/build-scheduler.js
- src/build.js
- test/env.json
- Renames most parts of the application to `pages`
- Leaves the federalist specific pipeline alone
- Leaves the `'federalist-deploy-user'`; I wasn't sure where this user/credential was created and didn't want to break the build (also matches the name of the cf space)
Renaming includes some deployment keys/application names
> rename application and methods to pages

- src/queue-client.js
- test/helpers.js
- test/queue-client-test.js
- Adds check for active jobs when there are none in the waiting queue
- Jobs are moved from `waiting` to `active` if there is not enough build containers available
None
> fix: Add check for active jobs when no queued jobs are in waiting

- .cloudgov/manifest.yml
This will bump update the large site build to 7GB of disk storage. The platform update has deployed via issue https://github.com/cloud-gov/product/issues/2339.
- Bumps the disk storage for a large site build container to 7GB
None
> chore: Bump custom disk for large site builds to 7GB

- .cloudgov/manifest.yml
A part of https://github.com/cloud-gov/pages-core/issues/4054
- Update app manifest to use stack cflinuxfs4
Updates underlining linux stack the app will run on
> choir: Update app to use cflinuxfs4 stack

- package.json
- yarn.lock
- Bump axios to v1.6.5
- Run audit fix to update dependencies
- Updates dependencies via audit fix
- In support of the [Github GPG key rotation](https://github.blog/2024-01-16-rotating-credentials-for-github-com-and-new-ghes-patches/)
> chore: Run audit fix for dependencies
